### ISSUE TITLE
Error: Cannot mix different versions of joi schemas

### ISSUE THREAD

**Issue by tropicar** [easyops-cn/docusaurus-search-local#168]
According to the README i am using a correct version of the docusaurus and easyops-cn.
I have installed the https://github.com/easyops-cn/docusaurus-search-local with `yarn add @easyops-cn/docusaurus-search-local` and I have added this part to the config file:
```
module.exports = {
  title: 'DAppNode',
  tagline: 'Dinosaurs are cool',
  url: 'https://docs.dappnode.io/',
  baseUrl: '/',
  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',
  favicon: 'img/favicon.ico',
  organizationName: 'dappnode', // Usually your GitHub org/user name.
  projectName: 'DAppNode', // Usually your repo name.

...

 themes:[
    [
      require.resolve("@easyops-cn/docusaurus-search-local"),
      {
        hashed: true,
      },
    ],
  ]
};
```

These are the dependencies of the project;
```
  "dependencies": {
    "@docusaurus/core": "2.0.0-alpha.74",
    "@docusaurus/preset-classic": "2.0.0-alpha.74",
    "@easyops-cn/docusaurus-search-local": "^0.23.2",
    "@mdx-js/react": "^1.6.21",
    "@types/react": "17.0.37",
    "clsx": "^1.1.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
```

The full logs  of the error are the next:
```
tropicar@TropicarPC:~/Desktop/dappnode/DAppNodeDocs$ yarn start
yarn run v1.22.10
$ docusaurus start
Starting the development server...
Error: Cannot mix different versions of joi schemas
    at new module.exports (/home/tropicar/Desktop/dappnode/DAppNodeDocs/node_modules/@hapi/hoek/lib/error.js:23:19)
    at module.exports (/home/tropicar/Desktop/dappnode/DAppNodeDocs/node_modules/@hapi/hoek/lib/assert.js:20:11)
    at Object.exports.isSchema (/home/tropicar/Desktop/dappnode/DAppNodeDocs/node_modules/@easyops-cn/docusaurus-search-local/node_modules/joi/lib/common.js:132:5)
    at Object.internals.schema (/home/tropicar/Desktop/dappnode/DAppNodeDocs/node_modules/@easyops-cn/docusaurus-search-local/node_modules/joi/lib/compile.js:66:16)
    at Object.exports.schema (/home/tropicar/Desktop/dappnode/DAppNodeDocs/node_modules/@easyops-cn/docusaurus-search-local/node_modules/joi/lib/compile.js:17:26)
    at internals.Base.$_compile (/home/tropicar/Desktop/dappnode/DAppNodeDocs/node_modules/@easyops-cn/docusaurus-search-local/node_modules/joi/lib/base.js:645:24)
    at /home/tropicar/Desktop/dappnode/DAppNodeDocs/node_modules/@easyops-cn/docusaurus-search-local/node_modules/joi/lib/types/keys.js:260:92
    at Object.exports.tryWithPath (/home/tropicar/Desktop/dappnode/DAppNodeDocs/node_modules/@easyops-cn/docusaurus-search-local/node_modules/joi/lib/common.js:176:16)
    at internals.Base.method [as keys] (/home/tropicar/Desktop/dappnode/DAppNodeDocs/node_modules/@easyops-cn/docusaurus-search-local/node_modules/joi/lib/types/keys.js:260:32)
    at internals.Base.method [as append] (/home/tropicar/Desktop/dappnode/DAppNodeDocs/node_modules/@easyops-cn/docusaurus-search-local/node_modules/joi/lib/types/keys.js:189:29)
    at normalizePluginOptions (/home/tropicar/Desktop/dappnode/DAppNodeDocs/node_modules/@docusaurus/utils-validation/lib/validationUtils.js:33:32)
    at validateOptions (/home/tropicar/Desktop/dappnode/DAppNodeDocs/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/utils/validateOptions.js:34:12)
    at /home/tropicar/Desktop/dappnode/DAppNodeDocs/node_modules/@docusaurus/core/lib/server/plugins/init.js:55:29
    at Array.map (<anonymous>)
    at Object.initPlugins [as default] (/home/tropicar/Desktop/dappnode/DAppNodeDocs/node_modules/@docusaurus/core/lib/server/plugins/init.js:24:10)
    at Object.loadPlugins (/home/tropicar/Desktop/dappnode/DAppNodeDocs/node_modules/@docusaurus/core/lib/server/plugins/index.js:48:35)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by weareoutman** [comment]
Try `yarn why joi` to see why mixed versions

**Comment by tropicar** [comment]
The problem was solved by installing the current version of docusaurus, this one was very outdated.
