### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'substr')

### ISSUE THREAD

**Issue by junsulee75** [easyops-cn/docusaurus-search-local#250]
Posting an error I got today and sharing the resolution workaround. 

## Installation done successfully
Previous used installation command and configuration was like below.    
```
$ yarn add @easyops-cn/docusaurus-search-local
```

## Added configuration to `docusaurus.config.js`    

```
    themes: [
      // ... Your other themes.
      [
        require.resolve("@easyops-cn/docusaurus-search-local"),
        {
          // ... Your options.
          // `hashed` is recommended as long-term-cache of index file is possible.
          hashed: true,
          // For Docs using Chinese, The `language` is recommended to set to:
          // ```
          // language: ["en", "zh"],
          // ```
        },
      ],
    ],
});
```

During the search build on Docusaurus, got the following error.    

```
jsmacpro16:cloud kr050496$ yarn build
yarn run v1.22.10
...
Unable to build website for locale "en".
TypeError: Cannot read properties of undefined (reading 'substr')
    at processDocInfos (/Users/kr050496/bin/github/junsulee75/cloud/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/utils/processDocInfos.js:18:50)
    at Object.<anonymous> (/Users/kr050496/bin/github/junsulee75/cloud/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/utils/postBuildFactory.js:17:64)
    at Generator.next (<anonymous>)
    at /Users/kr050496/bin/github/junsulee75/cloud/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/kr050496/bin/github/junsulee75/cloud/node_modules/tslib/tslib.js:114:16)
    at Object.postBuild (/Users/kr050496/bin/github/junsulee75/cloud/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/utils/postBuildFactory.js:15:24)
    at /Users/kr050496/bin/github/junsulee75/cloud/node_modules/@docusaurus/core/lib/commands/build.js:158:22
    at Array.map (<anonymous>)
    at buildLocale (/Users/kr050496/bin/github/junsulee75/cloud/node_modules/@docusaurus/core/lib/commands/build.js:154:31)
error Command failed with exit code 1.
```

**Comment by junsulee75** [comment]
Upgrading Docusaurus version resolved the issue.    
Sharing the outputs.    

```
$ npx docusaurus --version
...
2.0.0-beta.6

$ yarn upgrade @docusaurus/core@latest @docusaurus/preset-classic@latest
$ npx docusaurus --version
2.0.1

$ yarn build
```
=> completed successfully.
