### ISSUE TITLE
Now getting error in build

### ISSUE THREAD

**Issue by dhitimedin** [easyops-cn/docusaurus-search-local#3]
Please find the error.

Creating an optimized production build...
Error: Cannot find module 'nodejieba'
Require stack:
- /Users/nishit/Documents/GitHub/docusaurus3/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/utils/tokenizer.js
- /Users/nishit/Documents/GitHub/docusaurus3/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/utils/buildIndex.js
- /Users/nishit/Documents/GitHub/docusaurus3/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/utils/postBuildFactory.js
- /Users/nishit/Documents/GitHub/docusaurus3/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js
- /Users/nishit/Documents/GitHub/docusaurus3/node_modules/@docusaurus/core/lib/server/plugins/init.js
- /Users/nishit/Documents/GitHub/docusaurus3/node_modules/@docusaurus/core/lib/server/plugins/index.js
- /Users/nishit/Documents/GitHub/docusaurus3/node_modules/@docusaurus/core/lib/server/index.js
- /Users/nishit/Documents/GitHub/docusaurus3/node_modules/@docusaurus/core/lib/commands/build.js
- /Users/nishit/Documents/GitHub/docusaurus3/node_modules/@docusaurus/core/lib/index.js
- /Users/nishit/Documents/GitHub/docusaurus3/node_modules/@docusaurus/core/bin/docusaurus.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/nishit/Documents/GitHub/docusaurus3/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/utils/tokenizer.js:6:45)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/nishit/Documents/GitHub/docusaurus3/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/utils/buildIndex.js:6:21)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by weareoutman** [comment]
Oops, I missed an import statement before. Fixed again. Try `npm install @easyops-cn/docusaurus-search-local` or `yarn add @easyops-cn/docusaurus-search-local` again (v0.7.1).

**Comment by dhitimedin** [comment]
Thanks! Build is working but somehow I am not getting any search results. My repository is dhitimedin/docusaurus3 and hosted page address is https://dhitimedin.github.io/docusaurus3/ . Can you help me understand what could be the issue?

**Comment by weareoutman** [comment]
I see, you're using versioning docs, but sorry that's currently not supported yet. I'll put it into my todo-list.

**Comment by dhitimedin** [comment]
> I see, you're using versioning docs, but sorry that's currently not supported yet. I'll put it into my todo-list.

oh! Thanks for the analysis. By when can I expect it? Is it an easy task or a difficult task? Let me know if I can be of any support. I want to avoid algolia, but none of the offline search works for me.

**Comment by weareoutman** [comment]
Actually for now there is a quick workaround for you, to set the plugin option `indexPages: true` (because your docs make my plugin recognized it fallback to pages 🤷‍♂️), that will make your search works, for now. Also notice this could break in future. But I'll let you know when there are breaking changes (CHANGELOG.md).

**Comment by dhitimedin** [comment]
> Actually for now there is a quick workaround for you, to set the plugin option `indexPages: true` (because your docs make my plugin recognized it fallback to pages 🤷‍♂️), that will make your search works, for now. Also notice this could break in future. But I'll let you know when there are breaking changes (CHANGELOG.md).

Thank You! I have implemented and it is working. Here is the link: https://dhitimedin.github.io/docusaurus3

**Comment by weareoutman** [comment]
You're welcome.
