### ISSUE TITLE
Can't start after installation

### ISSUE THREAD

**Issue by zjy365** [easyops-cn/docusaurus-search-local#370]
import path from "path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1197:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at module.exports (/Users/jingyang/work/sealos/docs/website/node_modules/import-fresh/index.js:32:59)
    at normalizePluginConfig (/Users/jingyang/work/sealos/docs/website/node_modules/@docusaurus/core/lib/server/plugins/configs.js:45:57)
    at /Users/jingyang/work/sealos/docs/website/node_modules/@docusaurus/core/lib/server/plugins/configs.js:99:60
[INFO] Docusaurus version: 2.4.3
Node version: v20.4.0
 ELIFECYCLE  Command failed with exit code 1.

**Comment by overdone** [comment]
I have the same issue. Maybe due to incompatibility with version 2 of Docusaurus. Version 0.36 works fine

**Comment by bentookey-yotta** [comment]
Same issue here on Docusaurus v2.4.3.

**Comment by zjy365** [comment]
> I have the same issue. Maybe due to incompatibility with version 2 of Docusaurus. Version 0.36 works fine

Thank you very much, it can be used after lowering the version

**Comment by weareoutman** [comment]
Should be fixed in v0.37.5

**Comment by weareoutman** [comment]
@societymartingale Try 0.38.1

**Comment by societymartingale** [comment]
@weareoutman , 0.38.1 worked, thanks!
