### ISSUE TITLE
Error occurs when building after adding "hi" or "th" to languages

### ISSUE THREAD

**Issue by andrew-polk** [easyops-cn/docusaurus-search-local#438]
`docusaurus build` gives

TypeError: Cannot read properties of undefined (reading 'init')
[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at C:\dev\bloom-docs\node_modules\@docusaurus\core\lib\webpack\utils.js:180:24
    at C:\dev\bloom-docs\node_modules\webpack\lib\MultiCompiler.js:631:14
    at processQueueWorker (C:\dev\bloom-docs\node_modules\webpack\lib\MultiCompiler.js:568:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[INFO] Docusaurus version: 2.4.3
Node version: v18.16.0
error Command failed with exit code 1.

Seems to be caused by https://github.com/MihaiValentin/lunr-languages/issues/101.

**Comment by andrew-polk** [comment]
Note that while I am using docusaurus v2, this error occurs with v3 as well.
I used https://docusaurus.new/, just added the dependency, and added 
```
  themes: [
    [
      require.resolve("@easyops-cn/docusaurus-search-local"),
      {
        language: ["en", "hi"]
      },
    ],
  ],
```
to the config. 

That gave:  
```
[ERROR] Error: Unable to build website for locale en.
    at tryToBuildLocale (/project/workspace/node_modules/@docusaurus/core/lib/commands/build.js:54:19)
    at async /project/workspace/node_modules/@docusaurus/core/lib/commands/build.js:65:9
    at async mapAsyncSequential (/project/workspace/node_modules/@docusaurus/utils/lib/jsUtils.js:20:24)
    at async Command.build (/project/workspace/node_modules/@docusaurus/core/lib/commands/build.js:63:5) {
  [cause]: TypeError: Cannot read properties of undefined (reading 'init')
      at server.bundle.js:16693:15
      at 1088 (server.bundle.js:14194:70)
      at __webpack_require__ (server.bundle.js:28127:42)
      at 7401 (server.bundle.js:11585:24)
      at __webpack_require__ (server.bundle.js:28127:42)
      at 7489 (server.bundle.js:8814:14)
      at __webpack_require__ (server.bundle.js:28127:42)
      at 6533 (server.bundle.js:9695:21)
      at __webpack_require__ (server.bundle.js:28127:42)
      at server.bundle.js:28193:37
}
```

**Comment by weareoutman** [comment]
Seems to be a lunr / lunr-languages issue, please share the result of `yarn why lunr` and `yarn why lunr-languages`

**Comment by krishna-kush** [comment]
I'm having the same issue, But seeing this a 2 year old issue. Is it fixed and it's not my issue? Which I don't think. Then please tell me if it's the same.

Upon asking AI, the answer I seems to getting is the bug is actually in lunr-languages: the bug `Cannot read properties of undefined (reading 'init')` is a classic Server-Side Rendering (SSR) crash. As the Hindi tokenizer script was written under the assumption that it would only ever run inside a web browser. It looks for a global browser object to attach its .init() function to. Because it is running inside Node.js during the build process, that browser context is undefined. The script panics, and the build fatally crashes.

**My Error:**
```
[cause]: TypeError: Cannot read properties of undefined (reading 'init')
      at server.bundle.js:34060:15
      at 86897 (server.bundle.js:23346:27)
      at __webpack_require__ (server.bundle.js:39180:31)
      at 79527 (server.bundle.js:33843:114)
      at __webpack_require__ (server.bundle.js:39180:31)
      at 50957 (server.bundle.js:32863:70)
      at __webpack_require__ (server.bundle.js:39180:31)
      at 33666 (server.bundle.js:33422:48)
      at __webpack_require__ (server.bundle.js:39180:31)
      at 74968 (server.bundle.js:29633:54)
}
[INFO] Docusaurus version: 3.10.1
Node version: v22.21.1
```

**Comment by weareoutman** [comment]
This is fixed in v0.55.2

Root cause is some languages such as th and hi, need importing `lunr-languages/wordcut.js`, which is not documented, but only seen in language specific demo html.
