### ISSUE TITLE
Build fail on Docusaurus 3.5.1

### ISSUE THREAD

**Issue by ld-web** [easyops-cn/docusaurus-search-local#444]
Hello, first, thank you for this plugin !

I just upgraded to the newest version of Docusaurus (3.5.1) but I can't build with it :

```bash
[ERROR] Error: Unable to build website for locale fr.
    at tryToBuildLocale (/node_modules/.pnpm/@docusaurus+core@3.5.1_@docusaurus+types@3.5.1_react-dom@18.3.1_react@18.3.1__react@18.3.1__d_upty6jj6xlpwwmkc3vds73poq4/node_modules/@docusaurus/core/lib/commands/build.js:54:19)
    at async /node_modules/.pnpm/@docusaurus+core@3.5.1_@docusaurus+types@3.5.1_react-dom@18.3.1_react@18.3.1__react@18.3.1__d_upty6jj6xlpwwmkc3vds73poq4/node_modules/@docusaurus/core/lib/commands/build.js:65:9
    at async mapAsyncSequential (/node_modules/.pnpm/@docusaurus+utils@3.5.1_@docusaurus+types@3.5.1_react-dom@18.3.1_react@18.3.1__react@18.3.1__typescript@5.4.5/node_modules/@docusaurus/utils/lib/jsUtils.js:21:24)
    at async Command.build (/node_modules/.pnpm/@docusaurus+core@3.5.1_@docusaurus+types@3.5.1_react-dom@18.3.1_react@18.3.1__react@18.3.1__d_upty6jj6xlpwwmkc3vds73poq4/node_modules/@docusaurus/core/lib/commands/build.js:63:5) {
  [cause]: TypeError: Cannot read properties of undefined (reading 'load')
      at parse (/node_modules/.pnpm/@easyops-cn+docusaurus-search-local@0.39.0_@docusaurus+theme-common@3.5.1_@docusaurus+plugin-_btcdilkjrraiu2f6hyizxb3upy/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/utils/parse.js:10:33)
      at /node_modules/.pnpm/@easyops-cn+docusaurus-search-local@0.39.0_@docusaurus+theme-common@3.5.1_@docusaurus+plugin-_btcdilkjrraiu2f6hyizxb3upy/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/utils/scanDocuments.js:24:46
      at Generator.next (<anonymous>)
      at fulfilled (/node_modules/.pnpm/tslib@2.6.3/node_modules/tslib/tslib.js:166:62)
}
```

Docusaurus version: 3.5.1
Node version: v20.11.1

It looks like it can't `load` something with the cheerio package, but I have no idea what it is.

I tried to change the locale (both in Docusaurus and plugin configuration) but got the same error with `en` locale.

**Comment by hsm207** [comment]
I get the same error to when upgrading to docusaurus 3.5.1.

I'm using node v22.6.0.

**Comment by rainecheck** [comment]
I didn't get it on upgrade to 3.5.1, but I did get it after refreshing lockfile dependencies afterwards.

**Comment by weareoutman** [comment]
What's the output of `yarn why cheerio` or `npm list cheerio`?

**Comment by weareoutman** [comment]
Fixed in [v0.44.5](https://github.com/easyops-cn/docusaurus-search-local/releases/tag/v0.44.5)

**Comment by rainecheck** [comment]
Appears to be fixed in 0.44.5.

**Comment by ld-web** [comment]
Yes, works for me in v0.44.5.

謝謝 !

**Comment by hsm207** [comment]
It’s working for me in v0.44.5 too. 感謝你! ❤️
