### ISSUE TITLE
文档突然无法编译

### ISSUE THREAD

**Issue by Twiyin0** [easyops-cn/docusaurus-search-local#449]
好像是前几天的事，自从cheerio发布1.0.0后"@easyops-cn/docusaurus-search-local": "^0.23.1"就无法编译了  
```
[ERROR] Unable to build website for locale zh.
[ERROR] TypeError: Cannot read properties of undefined (reading 'load')
    at Object.parse (I:\github\docs.womadao.top\node_modules\@easyops-cn\docusaurus-search-local\dist\server\server\utils\parse.js:9:33)     
    at Object.<anonymous> (I:\github\docs.womadao.top\node_modules\@easyops-cn\docusaurus-search-local\dist\server\server\utils\scanDocuments.js:24:65)
    at Generator.next (<anonymous>)
    at fulfilled (I:\github\docs.womadao.top\node_modules\tslib\tslib.js:166:62)
[INFO] Docusaurus version: 2.4.3
Node version: v20.11.0
error Command failed with exit code 1.
```
以下是我的配置
```
i18n: {
  defaultLocale: 'zh',
  locales: ['en', 'zh'],
  localeConfigs: {
    zh: {
      htmlLang: 'zh-Hans',
    },
  },
},

require.resolve("@easyops-cn/docusaurus-search-local"),
{
  hashed: true,
  language: ["zh"],
  indexDocs: true,
  indexBlog: true,
  docsRouteBasePath: '/docs',
  blogRouteBasePath: 'blog',
  // translations: {
  //     "search_placeholder": "搜索",
  //     "see_all_results": "查看所有结果",
  //     "no_results": "没有结果。",
  //     "search_results_for": "搜索结果\"{{ keyword }}\" ",
  //     "search_the_documentation": "搜索文档",
  //     "count_documents_found": "{{ count }} 个文档找到",
  //     "count_documents_found_plural": " {{ count }} 个文件找到",
  //     "no_documents_were_found": "没有找到文件"
  // }
},
```
在此之前只是修改了.md中的内容
node版本试过18.16.0和20.11.0都是这个提示，如果把translations取消注释会报错像这样
![acea60b4cda6bd80e4ad9b3134c272df](https://github.com/user-attachments/assets/80840c4f-4c09-402c-8ff3-db39daab4a7e)
Docusaurus 版本: 2.4.3
@easyops-cn/docusaurus-search-local版本：0.23.1

**Comment by zboMa** [comment]
请问是如何解决的？

**Comment by weareoutman** [comment]
Duplicated as https://github.com/easyops-cn/docusaurus-search-local/issues/444

**Comment by Twiyin0** [comment]
把docusaurus升级到最新，它会告诉你哪里的链接坏掉了，你慢慢修复链接就行

**Comment by zboMa** [comment]
感谢各位！
