### ISSUE TITLE
run in docker image node:14.14.0-buster-slim error

### ISSUE THREAD

**Issue by monsterboom** [easyops-cn/docusaurus-search-local#54]
all the package is installed.
command 'npm run build '

Server: Compiled successfully

but log a error:
error building locale=en
Error: /app/node_modules/nodejieba/build/Release/nodejieba.node: invalid ELF header
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/app/node_modules/nodejieba/index.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/app/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/utils/tokenizer.js:6:45)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ls-docs-web@0.0.0 build: `docusaurus build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ls-docs-web@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-18T08_00_32_870Z-debug.log

**Comment by weareoutman** [comment]
For `invalid ELF header`, according to https://stackoverflow.com/a/29994851/14148700:

> This happens when you build on one architecture and then attempt to use the same built addon on a different architecture (or platform in some cases).

This is probably a problem of [nodejieba](https://github.com/yanyiwu/nodejieba) when using it on the docker image you used. I suggest you report a bug or a question to [nodejieba](https://github.com/yanyiwu/nodejieba/issues) instead.

**Comment by weareoutman** [comment]
And can you provide more information such as host system and arch (x86 or x86_64 or arm, etc,.)?

I just tried this image on my Mac x86_64, it works fine.
